[package]
name = "paft-money"
version.workspace = true
edition = "2024"
license.workspace = true
authors.workspace = true
description = "Currency and money primitives for the paft ecosystem."
repository.workspace = true
homepage = "https://github.com/paft-rs/paft"
documentation = "https://docs.rs/paft-money"
readme = "../README.md"
keywords = ["finance", "currency", "money", "serde"]
categories = ["finance", "data-structures"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
iso_currency = { workspace = true }
rust_decimal = { workspace = true }
paft-utils = { workspace = true }
df-derive = { workspace = true, optional = true }
polars = { workspace = true, features = ["lazy", "strings", "temporal", "serde", "regex", "timezones", "diagonal_concat", "json", "rolling_window", "dtype-decimal"], optional = true }

[features]
default = []
dataframe = ["polars", "df-derive"]
panicking-money-ops = []

[dev-dependencies]
serde_json = { workspace = true }

