# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**/*.md']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run lints
        run: just lint
      
      - name: Run tests
        run: just test
