name: Publish

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - features: rust-decimal
            args: "--no-default-features --features full,rust-decimal,panicking-money-ops"
          - features: bigdecimal
            args: "--no-default-features --features full,bigdecimal,panicking-money-ops"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: { components: clippy, rustfmt }
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-hack
      - run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - run: cargo hack nextest run --workspace --all-targets --ignore-unknown-features ${{ matrix.args }} --no-tests pass

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: { name: crates-io }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish (dry run)
        run: cargo publish --workspace --dry-run
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --workspace
